version: '3.9'

services:
  app:
    build: .
    container_name: mocktest-app
    ports:
      - "3000:3000"
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=123456
      - DB_NAME=mocktest
    depends_on:
      - db

  db:
    image: mysql:8
    container_name: mocktest-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: mocktest
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
